name: Test unit and instrumented

on: workflow_call

jobs:
  unit_tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: ./gradlew test

  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          script: ./gradlew connectedAndroidTest